image: Visual Studio 2022

shallow_clone: true

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build Rebus.TestHelpers -c Release 
  - dotnet build Rebus.TestHelpers.Tests -c Release 

test_script:
  - dotnet test